"""Add modulo_id to menus

Revision ID: 0cb6214ec9fd
Revises: a1b2c3d4e5f6
Create Date: 2026-07-15 21:26:36.231118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cb6214ec9fd'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('modulo_id', sa.UUID(as_uuid=False), nullable=True, comment='Módulo al que pertenece este menú'))
    op.create_index(op.f('ix_menus_modulo_id'), 'menus', ['modulo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menus_modulo_id'), table_name='menus')
    op.drop_column('menus', 'modulo_id')
    # ### end Alembic commands ###
