"""initial schema

Revision ID: f2bbe6958469
Revises: 
Create Date: 2026-07-04 19:50:59.184309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2bbe6958469'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
    sa.Column('texto', sa.String(length=150), nullable=False, comment="Texto visible del ítem en la UI (ej: 'Gestión de Usuarios')"),
    sa.Column('url', sa.String(length=500), nullable=True, comment='Ruta de navegación. NULL si es un contenedor padre (no hoja).'),
    sa.Column('icono', sa.String(length=100), nullable=True, comment="Clase de ícono CSS (ej: 'fas fa-users') para el frontend"),
    sa.Column('orden', sa.String(length=10), nullable=True, comment="Orden de renderizado entre ítems del mismo nivel (ej: '001', '002')"),
    sa.Column('parent_id', sa.UUID(as_uuid=False), nullable=True, comment='UUID del menú padre. NULL si es elemento raíz.'),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False, comment='Identificador único UUID'),
    sa.Column('estado', sa.Enum('ACTIVO', 'INACTIVO', name='estado_enum'), nullable=False, comment='Estado del registro. Soft Delete: INACTIVO en vez de DELETE.'),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False, comment='Timestamp automático de creación (managed by ORM)'),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False, comment='Timestamp automático de última modificación (managed by ORM)'),
    sa.Column('creado_por', sa.UUID(as_uuid=False), nullable=True, comment='UUID del usuario que creó el registro (null si es auto-registro)'),
    sa.Column('actualizado_por', sa.UUID(as_uuid=False), nullable=True, comment='UUID del usuario que modificó el registro por última vez'),
    sa.ForeignKeyConstraint(['parent_id'], ['menus.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menus_estado'), 'menus', ['estado'], unique=False)
    op.create_index(op.f('ix_menus_parent_id'), 'menus', ['parent_id'], unique=False)
    op.create_table('modules',
    sa.Column('nombre', sa.String(length=100), nullable=False, comment='Nombre del módulo administrativo (ej: Ventas, RRHH)'),
    sa.Column('descripcion', sa.Text(), nullable=True, comment='Descripción opcional del módulo'),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False, comment='Identificador único UUID'),
    sa.Column('estado', sa.Enum('ACTIVO', 'INACTIVO', name='estado_enum'), nullable=False, comment='Estado del registro. Soft Delete: INACTIVO en vez de DELETE.'),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False, comment='Timestamp automático de creación (managed by ORM)'),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False, comment='Timestamp automático de última modificación (managed by ORM)'),
    sa.Column('creado_por', sa.UUID(as_uuid=False), nullable=True, comment='UUID del usuario que creó el registro (null si es auto-registro)'),
    sa.Column('actualizado_por', sa.UUID(as_uuid=False), nullable=True, comment='UUID del usuario que modificó el registro por última vez'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modules_estado'), 'modules', ['estado'], unique=False)
    op.create_index(op.f('ix_modules_nombre'), 'modules', ['nombre'], unique=True)
    op.create_table('roles',
    sa.Column('nombre', sa.String(length=100), nullable=False, comment='Nombre del rol (ej: ADMIN, VENDEDOR)'),
    sa.Column('descripcion', sa.Text(), nullable=True, comment='Descripción opcional del rol'),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False, comment='Identificador único UUID'),
    sa.Column('estado', sa.Enum('ACTIVO', 'INACTIVO', name='estado_enum'), nullable=False, comment='Estado del registro. Soft Delete: INACTIVO en vez de DELETE.'),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False, comment='Timestamp automático de creación (managed by ORM)'),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False, comment='Timestamp automático de última modificación (managed by ORM)'),
    sa.Column('creado_por', sa.UUID(as_uuid=False), nullable=True, comment='UUID del usuario que creó el registro (null si es auto-registro)'),
    sa.Column('actualizado_por', sa.UUID(as_uuid=False), nullable=True, comment='UUID del usuario que modificó el registro por última vez'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_estado'), 'roles', ['estado'], unique=False)
    op.create_index(op.f('ix_roles_nombre'), 'roles', ['nombre'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email único del usuario (usado como login)'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Hash bcrypt de la contraseña. NUNCA exponer en API.'),
    sa.Column('nombre', sa.String(length=100), nullable=True, comment='Nombre completo del usuario'),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False, comment='Identificador único UUID'),
    sa.Column('estado', sa.Enum('ACTIVO', 'INACTIVO', name='estado_enum'), nullable=False, comment='Estado del registro. Soft Delete: INACTIVO en vez de DELETE.'),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False, comment='Timestamp automático de creación (managed by ORM)'),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False, comment='Timestamp automático de última modificación (managed by ORM)'),
    sa.Column('creado_por', sa.UUID(as_uuid=False), nullable=True, comment='UUID del usuario que creó el registro (null si es auto-registro)'),
    sa.Column('actualizado_por', sa.UUID(as_uuid=False), nullable=True, comment='UUID del usuario que modificó el registro por última vez'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_estado'), 'users', ['estado'], unique=False)
    op.create_table('role_menus',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('menu_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creado_por', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'menu_id', name='uq_role_menu')
    )
    op.create_index(op.f('ix_role_menus_menu_id'), 'role_menus', ['menu_id'], unique=False)
    op.create_index(op.f('ix_role_menus_role_id'), 'role_menus', ['role_id'], unique=False)
    op.create_table('role_modules',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('module_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creado_por', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'module_id', name='uq_role_module')
    )
    op.create_index(op.f('ix_role_modules_module_id'), 'role_modules', ['module_id'], unique=False)
    op.create_index(op.f('ix_role_modules_role_id'), 'role_modules', ['role_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVO', 'INACTIVO', name='estado_user_role_enum'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creado_por', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('actualizado_por', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_role_modules_role_id'), table_name='role_modules')
    op.drop_index(op.f('ix_role_modules_module_id'), table_name='role_modules')
    op.drop_table('role_modules')
    op.drop_index(op.f('ix_role_menus_role_id'), table_name='role_menus')
    op.drop_index(op.f('ix_role_menus_menu_id'), table_name='role_menus')
    op.drop_table('role_menus')
    op.drop_index(op.f('ix_users_estado'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_nombre'), table_name='roles')
    op.drop_index(op.f('ix_roles_estado'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_modules_nombre'), table_name='modules')
    op.drop_index(op.f('ix_modules_estado'), table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_menus_parent_id'), table_name='menus')
    op.drop_index(op.f('ix_menus_estado'), table_name='menus')
    op.drop_table('menus')
    # ### end Alembic commands ###
